export interface Country {
  code: string; // ISO 3166-1 alpha-2
  name: string;
  dialCode: string; // E.164 calling code, e.g. "+233"
}

// ISO 3166-1 alpha-2 code -> regional indicator flag emoji
export function countryFlag(iso2: string): string {
  return iso2
    .toUpperCase()
    .replace(/./g, (c) => String.fromCodePoint(127397 + c.charCodeAt(0)));
}

export const countries: Country[] = [
  { code: "GH", name: "Ghana", dialCode: "+233" },
  { code: "NG", name: "Nigeria", dialCode: "+234" },
  { code: "TG", name: "Togo", dialCode: "+228" },
  { code: "CI", name: "Côte d'Ivoire", dialCode: "+225" },
  { code: "BF", name: "Burkina Faso", dialCode: "+226" },
  { code: "BJ", name: "Benin", dialCode: "+229" },
  { code: "SN", name: "Senegal", dialCode: "+221" },
  { code: "ML", name: "Mali", dialCode: "+223" },
  { code: "NE", name: "Niger", dialCode: "+227" },
  { code: "GN", name: "Guinea", dialCode: "+224" },
  { code: "SL", name: "Sierra Leone", dialCode: "+232" },
  { code: "LR", name: "Liberia", dialCode: "+231" },
  { code: "GM", name: "Gambia", dialCode: "+220" },
  { code: "GW", name: "Guinea-Bissau", dialCode: "+245" },
  { code: "CV", name: "Cabo Verde", dialCode: "+238" },
  { code: "CM", name: "Cameroon", dialCode: "+237" },
  { code: "ZA", name: "South Africa", dialCode: "+27" },
  { code: "KE", name: "Kenya", dialCode: "+254" },
  { code: "UG", name: "Uganda", dialCode: "+256" },
  { code: "TZ", name: "Tanzania", dialCode: "+255" },
  { code: "RW", name: "Rwanda", dialCode: "+250" },
  { code: "ET", name: "Ethiopia", dialCode: "+251" },
  { code: "EG", name: "Egypt", dialCode: "+20" },
  { code: "MA", name: "Morocco", dialCode: "+212" },
  { code: "DZ", name: "Algeria", dialCode: "+213" },
  { code: "TN", name: "Tunisia", dialCode: "+216" },
  { code: "ZM", name: "Zambia", dialCode: "+260" },
  { code: "ZW", name: "Zimbabwe", dialCode: "+263" },
  { code: "MW", name: "Malawi", dialCode: "+265" },
  { code: "MZ", name: "Mozambique", dialCode: "+258" },
  { code: "AO", name: "Angola", dialCode: "+244" },
  { code: "NA", name: "Namibia", dialCode: "+264" },
  { code: "BW", name: "Botswana", dialCode: "+267" },
  { code: "SD", name: "Sudan", dialCode: "+249" },
  { code: "SS", name: "South Sudan", dialCode: "+211" },
  { code: "CD", name: "DR Congo", dialCode: "+243" },
  { code: "CG", name: "Congo", dialCode: "+242" },
  { code: "GA", name: "Gabon", dialCode: "+241" },
  { code: "US", name: "United States", dialCode: "+1" },
  { code: "CA", name: "Canada", dialCode: "+1" },
  { code: "GB", name: "United Kingdom", dialCode: "+44" },
  { code: "IE", name: "Ireland", dialCode: "+353" },
  { code: "DE", name: "Germany", dialCode: "+49" },
  { code: "FR", name: "France", dialCode: "+33" },
  { code: "ES", name: "Spain", dialCode: "+34" },
  { code: "PT", name: "Portugal", dialCode: "+351" },
  { code: "IT", name: "Italy", dialCode: "+39" },
  { code: "NL", name: "Netherlands", dialCode: "+31" },
  { code: "BE", name: "Belgium", dialCode: "+32" },
  { code: "CH", name: "Switzerland", dialCode: "+41" },
  { code: "AT", name: "Austria", dialCode: "+43" },
  { code: "SE", name: "Sweden", dialCode: "+46" },
  { code: "NO", name: "Norway", dialCode: "+47" },
  { code: "DK", name: "Denmark", dialCode: "+45" },
  { code: "FI", name: "Finland", dialCode: "+358" },
  { code: "PL", name: "Poland", dialCode: "+48" },
  { code: "GR", name: "Greece", dialCode: "+30" },
  { code: "TR", name: "Türkiye", dialCode: "+90" },
  { code: "RU", name: "Russia", dialCode: "+7" },
  { code: "UA", name: "Ukraine", dialCode: "+380" },
  { code: "CN", name: "China", dialCode: "+86" },
  { code: "JP", name: "Japan", dialCode: "+81" },
  { code: "KR", name: "South Korea", dialCode: "+82" },
  { code: "IN", name: "India", dialCode: "+91" },
  { code: "PK", name: "Pakistan", dialCode: "+92" },
  { code: "BD", name: "Bangladesh", dialCode: "+880" },
  { code: "PH", name: "Philippines", dialCode: "+63" },
  { code: "ID", name: "Indonesia", dialCode: "+62" },
  { code: "MY", name: "Malaysia", dialCode: "+60" },
  { code: "SG", name: "Singapore", dialCode: "+65" },
  { code: "TH", name: "Thailand", dialCode: "+66" },
  { code: "VN", name: "Vietnam", dialCode: "+84" },
  { code: "AE", name: "United Arab Emirates", dialCode: "+971" },
  { code: "SA", name: "Saudi Arabia", dialCode: "+966" },
  { code: "QA", name: "Qatar", dialCode: "+974" },
  { code: "IL", name: "Israel", dialCode: "+972" },
  { code: "AU", name: "Australia", dialCode: "+61" },
  { code: "NZ", name: "New Zealand", dialCode: "+64" },
  { code: "BR", name: "Brazil", dialCode: "+55" },
  { code: "MX", name: "Mexico", dialCode: "+52" },
  { code: "AR", name: "Argentina", dialCode: "+54" },
  { code: "JM", name: "Jamaica", dialCode: "+1876" },
];
